trigger:
  branches:
    include:
    - master

steps:
- task: Npm@1
  displayName: Install Dependencies
  inputs: 
    command: custom
    customCommand: ci
- script: npm run build
  displayName: Build Production App

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.SourcesDirectory)/www
    ArtifactName: ProductionArtifact
  displayName: Publish Build Artifacts
    


    

      